run_mode: debug #debug release test

log:
  filename: logs/gin.log
  level: info  #debug info warn error panic fatal
  maxsize: 10
  maxbackup: 3
  maxage: 28
  compress: false

app:
  page-size: 10
  jwt-token-name: 'Auth-Token'
  jwt-secret: '23311111sdf@wsefsdf'
  admin-secret: '111111'

server:
  port : 8080
  read-timeout : 60
  write-timeout : 60

database:
  type : mysql
  user : root
  password : 123456
  host : 127.0.0.1:3306
  name : admin
  table-prefix :

elasticsearch:
  host: http://192.168.3.203:9200
  index: waf-events
  timeout: 5s
  user: elastic
  password: changme